### ISSUE TITLE
python apply-patches.py ./patches $ROS_WORKSPACE error

### ISSUE THREAD

**Issue by cfr** [wjwwood/ros-osx#6]
I have followed your instruction on Snow Leopard (does it supported?) and got:

$ python apply-patches.py ./patches $ROS_WORKSPACE

INFO   : Using patches path: /users/cfr/ros-osx/electric-lion-homebrew/patches
INFO   : Using ROS path: /Users/cfr/ros
Traceback (most recent call last):
  File "apply-patches.py", line 76, in <module>
    if stack_version != generate_stack_version(stack_name):
  File "apply-patches.py", line 42, in generate_stack_version
    temp = subprocess.check_output([os.path.join(path_to_ros, "ros/bin/rosversion"), name]).strip()
AttributeError: 'module' object has no attribute 'check_output'

**Comment by wjwwood** [comment]
My patches will not work because I have specified all the dependencies to be
`osx: lion:`.  So, as is they will not work on SnowLeopard.  In the future I
will try to back port to SnowLeopard.

Your specific problem there is that the check_output function is new in
Python 2.7, so you must be using Python 2.6 or earlier.

## 

```
William Woodall
Graduate Software Engineering
Auburn University
w@auburn.edu
wjwwood@gmail.com
williamjwoodall.com
```

**Comment by wjwwood** [comment]
The patches and newly released stacks should support snow leopard, but if you have any trouble with them open a new ticket.

**Comment by cfr** [comment]
Ehm, can't find the «like» button, thank you!
